package compounds

var seedCompounds = []Compound{
	{ID: "bpc-157", Name: "BPC-157", Aliases: []string{"Body Protection Compound", "Pentadecapeptide"}, Category: CategoryHealingRecovery, Mechanism: "Upregulates growth factor expression (VEGF, FGF), promotes angiogenesis, modulates nitric oxide system, accelerates tendon/ligament/muscle/gut healing", TypicalDoseMin: 200, TypicalDoseMax: 600, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous", "intramuscular", "oral"}, HalfLife: "4-6 hours", TypicalCycle: "4-8 weeks", Status: StatusVerified},
	{ID: "tb-500", Name: "TB-500", Aliases: []string{"Thymosin Beta-4 Fragment"}, Category: CategoryHealingRecovery, Mechanism: "Promotes cell migration and differentiation, upregulates actin, reduces inflammation, increases angiogenesis in injured tissue", TypicalDoseMin: 2000, TypicalDoseMax: 5000, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous", "intramuscular"}, TypicalCycle: "4-8 weeks", Status: StatusVerified},
	{ID: "thymosin-beta-4", Name: "Thymosin Beta-4", Aliases: []string{"TB4", "Tβ4"}, Category: CategoryHealingRecovery, Mechanism: "Full-length protein; promotes wound healing, tissue repair, cell migration, anti-inflammatory via NF-κB modulation", TypicalDoseMin: 1000, TypicalDoseMax: 5000, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous"}, TypicalCycle: "4-12 weeks", Status: StatusVerified},
	{ID: "ghk-cu", Name: "GHK-Cu", Aliases: []string{"Copper Peptide", "GHK-Copper"}, Category: CategoryHealingRecovery, Mechanism: "Copper-binding tripeptide; stimulates collagen synthesis, glycosaminoglycan production, tissue remodeling, and stem cell attraction", TypicalDoseMin: 1000, TypicalDoseMax: 3000, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous", "topical"}, TypicalCycle: "4-8 weeks", Status: StatusVerified},
	{ID: "kpv", Name: "KPV", Aliases: []string{"Alpha-MSH Fragment (11-13)"}, Category: CategoryHealingRecovery, Mechanism: "Tripeptide from alpha-MSH C-terminal; potent anti-inflammatory via NF-κB inhibition, antimicrobial, gut mucosal healing", TypicalDoseMin: 200, TypicalDoseMax: 500, DoseUnit: "mcg", CommonRoutes: []string{"oral", "subcutaneous", "topical"}, TypicalCycle: "4-8 weeks", Status: StatusVerified},
	{ID: "cjc-1295-no-dac", Name: "CJC-1295 (no DAC)", Aliases: []string{"Mod GRF 1-29"}, Category: CategoryGHSecretagogue, Mechanism: "GHRH analog; stimulates pulsatile GH release from pituitary, short half-life preserves natural GH pulsatility", TypicalDoseMin: 100, TypicalDoseMax: 300, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous"}, TypicalCycle: "8-12 weeks", Status: StatusVerified},
	{ID: "ipamorelin", Name: "Ipamorelin", Aliases: []string{"IPA"}, Category: CategoryGHSecretagogue, Mechanism: "Selective GH secretagogue (ghrelin mimetic); stimulates GH release without significant cortisol/prolactin increase", TypicalDoseMin: 100, TypicalDoseMax: 300, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous"}, TypicalCycle: "8-12 weeks", Status: StatusVerified},
	{ID: "semaglutide", Name: "Semaglutide", Aliases: []string{"Ozempic", "Wegovy", "Rybelsus"}, Category: CategoryBodyComposition, Mechanism: "GLP-1 receptor agonist; reduces appetite via hypothalamic signaling, slows gastric emptying, improves insulin sensitivity, cardiovascular benefits", TypicalDoseMin: 0.25, TypicalDoseMax: 2.4, DoseUnit: "mg", CommonRoutes: []string{"subcutaneous", "oral"}, TypicalCycle: "ongoing", Status: StatusVerified},
	{ID: "tirzepatide", Name: "Tirzepatide", Aliases: []string{"Mounjaro", "Zepbound"}, Category: CategoryBodyComposition, Mechanism: "Dual GIP/GLP-1 agonist; superior weight loss vs GLP-1 alone, improves glycemic control, enhances insulin secretion", TypicalDoseMin: 2.5, TypicalDoseMax: 15, DoseUnit: "mg", CommonRoutes: []string{"subcutaneous"}, TypicalCycle: "ongoing", Status: StatusVerified},
	{ID: "selank", Name: "Selank", Aliases: []string{"TP-7"}, Category: CategoryCognitive, Mechanism: "Tuftsin analog; anxiolytic via GABA modulation, enhances BDNF expression, modulates IL-6, improves memory consolidation", TypicalDoseMin: 250, TypicalDoseMax: 750, DoseUnit: "mcg", CommonRoutes: []string{"nasal", "subcutaneous"}, TypicalCycle: "2-4 weeks", Status: StatusVerified},
	{ID: "epithalon", Name: "Epithalon", Aliases: []string{"Epitalon", "Epithalone", "AEDG"}, Category: CategoryAntiAging, Mechanism: "Telomerase activator (pineal tetrapeptide); increases telomerase activity, regulates melatonin production, anti-aging bioregulator", TypicalDoseMin: 5000, TypicalDoseMax: 10000, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous"}, TypicalCycle: "10-20 day cycles, 2-3x/year", Status: StatusVerified},
	{ID: "thymosin-alpha-1", Name: "Thymosin Alpha-1", Aliases: []string{"Ta1", "Zadaxin"}, Category: CategoryImmune, Mechanism: "Thymic peptide; enhances T-cell maturation, dendritic cell activation, TLR signaling, NK cell activity; approved in 30+ countries", TypicalDoseMin: 1600, TypicalDoseMax: 3200, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous"}, TypicalCycle: "4-12 weeks", Status: StatusVerified},
	{ID: "pt-141", Name: "PT-141", Aliases: []string{"Bremelanotide", "Vyleesi"}, Category: CategorySexualHealth, Mechanism: "Melanocortin-4 receptor agonist; stimulates sexual arousal centrally (hypothalamus), FDA-approved for female HSDD", TypicalDoseMin: 1000, TypicalDoseMax: 2000, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous", "nasal"}, TypicalCycle: "as needed", Status: StatusVerified},
	{ID: "gonadorelin", Name: "Gonadorelin", Aliases: []string{"GnRH", "LHRH"}, Category: CategorySexualHealth, Mechanism: "Natural GnRH decapeptide; pulsatile administration maintains LH/FSH production, preserves fertility during testosterone therapy", TypicalDoseMin: 50, TypicalDoseMax: 100, DoseUnit: "mcg", CommonRoutes: []string{"subcutaneous"}, TypicalCycle: "ongoing with TRT", Status: StatusVerified},

	// Remaining compounds will be added as full seed data in Phase 1
	// This is a representative subset for SDK scaffolding
}
